//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acessos_trilha_auditoria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class change
    {
        public int id { get; set; }
        public string schema { get; set; }
        public string table { get; set; }
        public string action { get; set; }
        public string tuple { get; set; }
        public int id_log { get; set; }
    
        public virtual log log { get; set; }
    }
}
