//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acessos_trilha_auditoria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public log()
        {
            this.change = new HashSet<change>();
        }
    
        public int id { get; set; }
        public string ip { get; set; }
        public string agent { get; set; }
        public System.DateTime start_date { get; set; }
        public string user_name { get; set; }
        public string manchine_name { get; set; }
        public string cpf_user { get; set; }
        public string name_user { get; set; }
        public string calling_method_name { get; set; }
        public string http_method { get; set; }
        public string assembly_name { get; set; }
        public string database_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<change> change { get; set; }
    }
}
